# Generated by Django 2.1.2 on 2020-09-10 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200909_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_requested', models.DecimalField(decimal_places=0, max_digits=30)),
                ('price_requested', models.DecimalField(decimal_places=0, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='store',
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Purchase'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Store'),
        ),
    ]
