# Generated by Django 2.1.2 on 2020-09-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_storemanager_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetail',
            name='store',
        ),
    ]
